name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build APK via Bubblewrap
        run: |
          npm install -g @bubblewrap/cli
          yes "N" | npx @bubblewrap/cli init --manifest=https://raw.githubusercontent.com/${{ github.repository }}/main/manifest.json
          npx @bubblewrap/cli build --skipSigning

      - name: Save APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Interactive-Whiteboard-APK
          path: ./*.apk
